project:
  type: website

website:
  title: "Primer course week 3 solution"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - sidebar:sources
      - sidebar:interactive
  sidebar: 
    - id: sources
      title: "Sources"
      style: "docked"
      background: "#ffffff"
      collapse-level: 2
      contents:
        - source-1.qmd
        - source-2.qmd
    - id: interactive
      title: "Interactive Pages"
      style: "floating"
      background: "#ffffff"
      collapse-level: 3
      contents:
        - plane-passengers.qmd
        - map-london.qmd
        - plotly.qmd


format:
  html:
    theme: Cyberg
    css: bootstrap.min
    toc: true

editor: source

